name: EGSOres
main: com.nannerss.eternalore.EternalOre
version: 1.2.1
authors: [Nannerss, TheMelvinNL]

api-version: 1.13

permissions:
  eternalore.*:
    description: Grants player all permissions for this plugin. Be careful with who you give this to.
    default: false
    children:
      eternalore.help: true
      eternalore.respawn: true
      eternalore.reload: true
      eternalore.wand.give: true
      eternalore.wand.use: true
      eternalore.update: true
  eternalore.help:
    description: Allows the player to view the help for this plugin.
    default: false
  eternalore.respawn:
    description: Allows the player to respawn mined ores.
    default: false
  eternalore.reload:
    description: Allows the player to reload the settings.yml
    default: false
  eternalore.wand.give:
    description: Allows the player to give themself the Eternal Ore Wand.
    default: false
  eternalore.wand.use:
    description: Allows the player to use the Eternal Ore Wand.
    default: false
  eternalore.update:
    description: Allows the player to recieve a plugin update message on join.
    default: false